version: '2'
services:
    mysqldb:
        image: mysql
        ports:
            - 3030:3306
        environment:
            MYSQL_DATABASE: evento
            MYSQL_ROOT_PASSWORD: 1234

    s3app:
        build:
            dockerfile: Dockerfile
        image: backendimage:latest
        restart: always
        ports:
            - 8080:8080
        environment:
            MYSQL_HOST: mysqldb
            MYSQL_USER: root
            MYSQL_PASSWORD: 1234
            MYSQL_PORT: 3306
        depends_on: 
            - mysqldb

    app-client:
        build:
            context: ../eventofront/
            dockerfile: ../eventofront/Dockerfile
            args:
                    REACT_APP_API_BASE_URL: http://127.0.0.1:8080
        image: frontendimage
        ports:
            - "3000:3000" # Map the exposed port 80 on the container to port 9090 on the host machine
        restart: always
        depends_on:
            - s3app